# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c6b015c94933f77990c8e3db6c6674bdf7d6f050b725f582c42edefc993ccb1cab4e9b1845dffcf81515eb2ce159ff301141fd8a39e143426208c2ff14e8a72

test:
  secret_key_base: 9c05b1260e7cca8111ad319a64bad63ae63d85676a05ede0900f5047d155722b2fae28aac23676caffec1db1f24c27a4013cf4d38a6abe4296a2592f626073d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
